# Generated by Django 3.0.5 on 2020-04-30 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcap_geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes_id', models.CharField(db_index=True, help_text='Required. At most 15 digits.', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$')], verbose_name='CNES registry')),
                ('name', models.CharField(help_text='Required. At most 150 characters.', max_length=150, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the healthcare unit can be used by the system.', verbose_name='active')),
                ('city', models.ForeignKey(help_text='Required.', on_delete=django.db.models.deletion.CASCADE, related_name='city_healthcare_units', to='hcap_geo.Region', verbose_name='city')),
                ('country', models.ForeignKey(editable=False, help_text='It will be defined according to the state.', on_delete=django.db.models.deletion.CASCADE, related_name='country_healthcare_units', to='hcap_geo.Region', verbose_name='country')),
                ('state', models.ForeignKey(editable=False, help_text='It will be defined according to the city.', on_delete=django.db.models.deletion.CASCADE, related_name='state_healthcare_units', to='hcap_geo.Region', verbose_name='state')),
            ],
            options={
                'verbose_name': 'healthcare unit',
                'verbose_name_plural': 'healthcare units',
                'ordering': ('country', 'state', 'city', 'name'),
                'unique_together': {('country', 'cnes_id')},
            },
        ),
    ]
