# Generated by Django 3.0.5 on 2020-04-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20200410_1420")]

    operations = [
        migrations.RemoveField(model_name="user", name="is_state_manager"),
        migrations.RemoveField(model_name="user", name="is_verified_notifier"),
        migrations.AddField(
            model_name="user",
            name="is_authorized",
            field=models.BooleanField(
                default=False,
                help_text="Marque para usuários autorizados a operar dentro do seu papel.",
                verbose_name="Autorizado?",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Nenhum"), (1, "Notificador"), (2, "Gestor local")],
                default=0,
                help_text="O usuário é notificador ou gestor?",
                verbose_name="Papel do usuário",
            ),
        ),
    ]
