{
 "title": "Capacidade Hospitalar",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Número absoluto de Casos Covid-19 por Estado",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cases_covid_adult_daily + cases_covid_pediatric_daily + cases_icu_covid_adult_daily + cases_icu_covid_pediatric_daily",
     "legendFormat": "{{uf}}"
    }
   ]
  },
  {
   "title": "Total de Casos de COVID-19 por Estado",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cases_covid_adult_daily + cases_covid_pediatric_daily + cases_icu_covid_adult_daily + cases_icu_covid_pediatric_daily",
     "legendFormat": "{{uf}}"
    }
   ]
  },
  {
   "title": "Número Total de Casos de Covid no Brasil",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(cases_covid_adult_daily + cases_covid_pediatric_daily + cases_icu_covid_adult_daily + cases_icu_covid_pediatric_daily)"
    }
   ]
  },
  {
   "title": "Número absoluto de Casos SRAG por Estado",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "cases_sari_adult_daily + cases_sari_pediatric_daily + cases_icu_sari_adult_daily + cases_icu_sari_pediatric_daily",
     "legendFormat": "{{uf}}"
    }
   ]
  },
  {
   "title": "Total de Casos de SRAG por Estado",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cases_sari_adult_daily + cases_sari_pediatric_daily + cases_icu_sari_adult_daily + cases_icu_sari_pediatric_daily",
     "legendFormat": "{{uf}}"
    }
   ]
  },
  {
   "title": "Número Total de Casos de SRAG no Brasil",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(cases_sari_adult_daily + cases_sari_pediatric_daily + cases_icu_sari_adult_daily + cases_icu_sari_pediatric_daily)"
    }
   ]
  },
  {
   "title": "Top 5 Percentual de Unidades Não Ativas",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "((sum by (uf) (healthcare_units{is_active=\"False\"})) / (sum by (uf) (healthcare_units))) * 100",
     "legendFormat": "{{uf}}"
    }
   ]
  },
  {
   "title": "Unidades de Saúde Ativas por Estado",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "healthcare_units{is_active=\"True\"}",
     "legendFormat": "{{uf}}"
    }
   ]
  },
  {
   "title": "Unidades de Saúde Inativas por Estado",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "healthcare_units{is_active=\"False\"}",
     "legendFormat": "{{uf}}"
    }
   ]
  }
 ]
}