# Generated by Django 3.0.3 on 2020-04-07 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'Capacidade', 'verbose_name_plural': 'Valores de capacidade'},
        ),
        migrations.AlterModelOptions(
            name='healthcareunity',
            options={'verbose_name': 'Estabelecimento de Saúde', 'verbose_name_plural': 'Estabelecimentos de Saúde'},
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': 'Entrada de caso', 'verbose_name_plural': 'Entradas de casos'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'permissions': [('fill', 'Pode adicionar lista de estados no banco')], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='healthcareunity',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Unidade foi validada por um gestor?'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='beds_adults',
            field=models.PositiveSmallIntegerField(help_text='Informe a capacidade total.', verbose_name='Leitos clínicos de adultos'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='beds_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe a capacidade total.', verbose_name='Leitos clínicos pediátricos'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='icu_adults',
            field=models.PositiveSmallIntegerField(help_text='Informe a capacidade total.', verbose_name='Leitos UTI adulto'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='icu_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe a capacidade total.', verbose_name='Leitos UTI pediátrico'),
        ),
        migrations.AlterField(
            model_name='healthcareunity',
            name='phone',
            field=models.CharField(help_text='Utilize o formato (XX) XXXXX-XXXX', max_length=150, validators=[django.core.validators.RegexValidator('\\(\\d{2}\\)\\s?\\d{4,5}-?\\d{4}', 'Não esqueça dos parênteses e hífens no número de telefone')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='covid_cases_adults',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos casos de COVID dentro dessa categoria.', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='covid_cases_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos casos de COVID dentro dessa categoria.', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='covid_casesadults',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos casos de COVID dentro dessa categoria.', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='covid_casespediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos casos de COVID dentro dessa categoria.', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_beds_adults',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos clínicos de adultos (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_beds_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos clínicos pediátricos (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_icu_adults',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos UTI adulto (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_icu_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos UTI pediátrico (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sari_beds_adults',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupados apenas por Síndrome Respiratória Aguda Grave', verbose_name='Ocupação de leitos clínicos de adultos por SRAG'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sari_beds_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupados apenas por Síndrome Respiratória Aguda Grave', verbose_name='Ocupação de leitos clínicos pediátricos por SRAG'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sari_icu_adults',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupado apenas por Síndrome Respiratória Aguda Grave.', verbose_name='Ocupação de leitos UTI adulto por SRAG'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sari_icu_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Informe quantos leitos deste tipo estão ocupado apenas por Síndrome Respiratória Aguda Grave.', verbose_name='Ocupação de leitos UTI pediátrico por SRAG'),
        ),
    ]
