# Generated by Django 3.0.5 on 2020-04-09 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logentry", old_name="regular_icu_adults", new_name="icu_regular_adults"
        ),
        migrations.RenameField(
            model_name="logentry",
            old_name="regular_icu_pediatric",
            new_name="icu_regular_pediatric",
        ),
        migrations.AlterField(
            model_name="healthcareunity",
            name="notifiers",
            field=models.ManyToManyField(
                related_name="healthcare_unities", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
