# Generated by Django 3.0.5 on 2020-04-10 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200409_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Quando ocorreu a alteração na capacidade hospitalar?', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='De quando é este dado?', verbose_name='Data'),
        ),
    ]
