# Generated by Django 3.0.5 on 2020-04-11 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_fill_healthcare_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifierForHealthcareUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "notifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.HealthcareUnit"
                    ),
                ),
            ],
        )
    ]
