# Generated by Django 3.0.5 on 2020-04-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200408_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareunity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Unidade está ativa?'),
        ),
    ]
