# Generated by Django 3.0.5 on 2020-04-12 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_fill_healthcare_units")]

    operations = [
        migrations.AlterField(
            model_name="healthcareunit",
            name="cnes_id",
            field=models.CharField(
                db_index=True,
                max_length=15,
                validators=[django.core.validators.RegexValidator("[0-9]+")],
                verbose_name="Registro CNES",
            ),
        )
    ]
