# Generated by Django 3.0.5 on 2020-04-08 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_healthcareunity_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'Capacidade', 'verbose_name_plural': 'Alterações de capacidade hospitalar'},
        ),
        migrations.AddField(
            model_name='capacity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Quando ocorreu a alteração na capacidade hospitalar?', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='beds_adults',
            field=models.PositiveSmallIntegerField(help_text='Quantos leitos deste tipo você tem?', verbose_name='Adulto'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='beds_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Quantos leitos deste tipo você tem?', verbose_name='Pediátrico'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='icu_adults',
            field=models.PositiveSmallIntegerField(help_text='Quantos leitos deste tipo você tem?', verbose_name='Adulto'),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='icu_pediatric',
            field=models.PositiveSmallIntegerField(help_text='Quantos leitos deste tipo você tem?', verbose_name='Pediátrico'),
        ),
    ]
