# Generated by Django 3.0.5 on 2020-04-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0003_notifierforhealthcareunit")]

    operations = [migrations.RemoveField(model_name="healthcareunit", name="notifiers")]
