# Generated by Django 3.0.5 on 2020-04-08 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200408_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'Alteração na capacidade', 'verbose_name_plural': 'Alterações de capacidade hospitalar'},
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='covid_casesadults',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='covid_casespediatric',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='sari_icu_adults',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='sari_icu_pediatric',
        ),
        migrations.AddField(
            model_name='logentry',
            name='icu_covid_cases_adults',
            field=models.PositiveSmallIntegerField(default=0, help_text='Destes casos, quantos foram confirmados como COVID?', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='icu_covid_cases_pediatric',
            field=models.PositiveSmallIntegerField(default=0, help_text='Destes casos, quantos foram confirmados como COVID?', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='icu_sari_beds_adults',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe total de leitos com qualquer sintoma de SRAG', verbose_name='Adulto'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='icu_sari_beds_pediatric',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe total de leitos com qualquer sintoma de SRAG', verbose_name='Pediátrico'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='covid_cases_adults',
            field=models.PositiveSmallIntegerField(default=0, help_text='Destes casos, quantos foram confirmados como COVID?', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='covid_cases_pediatric',
            field=models.PositiveSmallIntegerField(default=0, help_text='Destes casos, quantos foram confirmados como COVID?', verbose_name='Casos COVID confirmados'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='De quando é este dado?', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_beds_adults',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos clínicos de adultos (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_beds_pediatric',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos clínicos pediátricos (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_icu_adults',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos UTI adulto (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='regular_icu_pediatric',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe quantos leitos deste tipo estão ocupados.', verbose_name='Ocupação de leitos UTI pediátrico (outras causas)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sari_beds_adults',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe total de leitos com qualquer sintoma de SRAG', verbose_name='Adulto'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sari_beds_pediatric',
            field=models.PositiveSmallIntegerField(default=0, help_text='Informe total de leitos com qualquer sintoma de SRAG', verbose_name='Pediátrico'),
        ),
    ]
