# Generated by Django 3.0.5 on 2020-04-08 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200408_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='icu_sari_beds_adults',
            new_name='icu_sari_cases_adults',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='icu_sari_beds_pediatric',
            new_name='icu_sari_cases_pediatric',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='regular_beds_adults',
            new_name='regular_cases_adults',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='regular_beds_pediatric',
            new_name='regular_cases_pediatric',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='sari_beds_adults',
            new_name='sari_cases_adults',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='sari_beds_pediatric',
            new_name='sari_cases_pediatric',
        ),
    ]
