# Generated by Django 3.0.5 on 2020-04-30 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import hcap_utils.contrib.validations.date_not_from_future_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcap_accounts', '0001_initial'),
        ('hcap_institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareUnitCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today, help_text='Required. Date from which the healthcare unit changed its condition.', validators=[hcap_utils.contrib.validations.date_not_from_future_validator.DateNotFromFutureValidator()], verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sari_adult_clinical_cases', models.PositiveSmallIntegerField(help_text='Required. Includes confirmed COVID adult cases. Excludes SARI adult ICU cases.', verbose_name='SARI adult clinical cases')),
                ('covid_adult_clinical_cases', models.PositiveSmallIntegerField(help_text='Required. Excludes confirmed COVID adult ICU cases', verbose_name='confirmed COVID adult clinical cases')),
                ('sari_pediatric_clinical_cases', models.PositiveSmallIntegerField(help_text='Required. Includes confirmed COVID pediatric cases. Excludes SARI pediatric ICU cases.', verbose_name='SARI pediatric clinical cases')),
                ('covid_pediatric_clinical_cases', models.PositiveSmallIntegerField(help_text='Required. Excludes confirmed COVID pediatric ICU cases.', verbose_name='confirmed COVID pediatric clinical cases')),
                ('sari_adult_icu_cases', models.PositiveSmallIntegerField(help_text='Required. Includes confirmed COVID adult ICU cases.', verbose_name='SARI adult ICU cases')),
                ('covid_adult_icu_cases', models.PositiveSmallIntegerField(help_text='Required.', verbose_name='confirmed COVID adult ICU cases')),
                ('sari_pediatric_icu_cases', models.PositiveSmallIntegerField(help_text='Required. Includes confirmed COVID pediatric ICU cases.', verbose_name='SARI pediatric ICU cases')),
                ('covid_pediatric_icu_cases', models.PositiveSmallIntegerField(help_text='Required.', verbose_name='confirmed COVID pediatric ICU cases')),
                ('general_adult_clinical_cases', models.PositiveSmallIntegerField(help_text='Required. Excludes SARI adult clinical cases and general adult ICU cases.', verbose_name='general adult clinical cases')),
                ('general_pediatric_clinical_cases', models.PositiveSmallIntegerField(help_text='Required. Excludes SARI pediatric clinical cases and general pediatric ICU cases.', verbose_name='general pediatric clinical cases')),
                ('general_adult_icu_cases', models.PositiveSmallIntegerField(help_text='Required. Excludes SARI adult ICU cases.', verbose_name='general adult ICU cases')),
                ('general_pediatric_icu_cases', models.PositiveSmallIntegerField(help_text='Required. Excludes SARI pediatric ICU cases.', verbose_name='general pediatric ICU cases')),
                ('healthcare_unit', models.ForeignKey(editable=False, help_text='It will be defined according to the notifier.', on_delete=django.db.models.deletion.CASCADE, related_name='condition_notifications', to='hcap_institutions.HealthcareUnit', verbose_name='healthcare unit')),
                ('notifier', models.ForeignKey(help_text='Required.', on_delete=django.db.models.deletion.CASCADE, related_name='condition_notifications', to='hcap_accounts.HealthcareUnitNotifier', verbose_name='notifier')),
            ],
            options={
                'verbose_name': 'healthcare unit condition',
                'verbose_name_plural': 'healthcare unit conditions',
                'ordering': ('healthcare_unit', 'date'),
                'unique_together': {('healthcare_unit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HealthcareUnitCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today, help_text='Required. Date from which the healthcare unit changed its capacity.', validators=[hcap_utils.contrib.validations.date_not_from_future_validator.DateNotFromFutureValidator()], verbose_name='date')),
                ('clinical_adult_beds', models.PositiveSmallIntegerField(help_text='Required.', verbose_name='clinical adult beds')),
                ('clinical_pediatric_beds', models.PositiveSmallIntegerField(help_text='Required.', verbose_name='clinical pediatric beds')),
                ('icu_adult_beds', models.PositiveSmallIntegerField(help_text='Required.', verbose_name='ICU adult beds')),
                ('icu_pediatric_beds', models.PositiveSmallIntegerField(help_text='Required.', verbose_name='ICU pediatric beds')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('healthcare_unit', models.ForeignKey(editable=False, help_text='It will be defined according to the notifier.', on_delete=django.db.models.deletion.CASCADE, related_name='capacity_notifications', to='hcap_institutions.HealthcareUnit', verbose_name='healthcare unit')),
                ('notifier', models.ForeignKey(help_text='Required.', on_delete=django.db.models.deletion.CASCADE, related_name='capacity_notifications', to='hcap_accounts.HealthcareUnitNotifier', verbose_name='notifier')),
            ],
            options={
                'verbose_name': 'healthcare unit capacity',
                'verbose_name_plural': 'healthcare unit capacities',
                'ordering': ('healthcare_unit', 'date'),
                'unique_together': {('healthcare_unit', 'date')},
            },
        ),
    ]
