# Generated by Django 3.0.5 on 2020-04-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagerForMunicipality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "ordering": ("name",),
                "permissions": [("fill", "Pode adicionar lista de estados no banco")],
            },
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="locations.State",
                    ),
                ),
            ],
            options={"verbose_name": "Município", "verbose_name_plural": "Municípios"},
        ),
    ]
