# Generated by Django 3.0.5 on 2020-04-08 12:45
import json
from pathlib import Path

from django.db import migrations


def fill_states(apps, schema_editor):
    State = apps.get_model("locations", "State")
    with open(Path(__file__).parent.parent / "data" / "states.json") as fd:
        data = json.load(fd)
    states = [State(**st) for st in data]
    State.objects.bulk_create(states)


def fill_cities(apps, schema_editor):
    Municipality = apps.get_model("locations", "Municipality")
    with open(Path(__file__).parent.parent / "data" / "cities.json") as fd:
        data = json.load(fd)

    def fix(d):
        del d["state_code"]
        return d

    cities = [Municipality(**fix(st)) for st in data]
    Municipality.objects.bulk_create(cities, batch_size=200)


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_states),
        migrations.RunPython(fill_cities),
    ]
