# Generated by Django 3.0.5 on 2020-04-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_auto_20200408_2239"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="state",
            options={
                "ordering": ("name",),
                "permissions": [("fill", "Pode adicionar lista de estados no banco")],
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
            },
        ),
    ]
